name: 'CI Create Release'

on:
  push:
    branches:
      - dev

jobs:
  update_release_draft:
    name: Release drafter
    runs-on: ubuntu-latest

    steps:
      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}