name: 'CI Update Release'

# on:
#   push:
#     branches:
#       - dev
# Will not be triggered on drafts
on:
  release:
    types: 
      - prereleased
      - released
      - published

jobs:
  update_release_draft:
    name: Release drafter
    runs-on: ubuntu-latest

    steps:
      - name: Update Release Draft
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  update_changelog:
    name: Update Changelog
    needs: update_release_draft
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ github.event.release.name }}
          release-notes: ${{ github.event.release.body }}

      # Requires permissions at the repository level : Settings -> Action -> General -> Workflow permissions and choose read and write permissions
      - name: Commit updated Changelog
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          branch: dev
          commit_message: 'docs(changelog): update changelog'
          file_pattern: CHANGELOG.md